notifications:
  email: false
sudo: false
language: python
os:
  -linux
  -osx
python:
  - 2.7
install:
  - pip install matplotlib
  - python setup.py -q install
 
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  
script:
  - python setup.py test
