notifications:
  email: false
sudo: false

language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 2.7

    - os: osx
      sudo: required
      language: generic

#  Manually install python on osx
install: pip install matplotlib |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      brew update;
      brew install python;
      python3 -m venv venv;
      source venv/bin/activate;
      pip install . test

  else
      pip install . test
  fi

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  
script: python setup.py test
