notifications:
  email: false
sudo: false

language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 2.7

    - os: osx
      sudo: required
      language: generic

#  Manually install python on osx
before_install: 
  
    
install: 
  - pip install matplotlib 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew install python;
    python2 setup.py install;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    python setup.py install;
    fi


before_script: # configure a headless display to test plot generation
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    "export DISPLAY=:99.0";
    "sh -e /etc/init.d/xvfb start";
    sleep 5;
    fi
  # give xvfb some time to start
  
script: python setup.py test
