notifications:
  email: false
sudo: false
language: python
python:
  - 2.7
install:
  - pip install matplotlib
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python setup.py -q install --user
 
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  
script:
  - python setup.py test
