notifications:
  email: false
sudo: false

language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 2.7

    - os: osx
      sudo: required
      language: generic

#  Manually install python on osx
before_install: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update;
    brew install mono;
    brew install pyenv;
    pyenv install $PYTHON;
    fi
    
install: 
  - pip install matplotlib 
  - python setup.py install

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  
script: python setup.py test
